local menu = cheadle_api.ImGui.Menu("Example Menu", 0)
menu:SetSize(400, 230)
menu:SetPos(100, 100)

local button = cheadle_api.ImGui.Button(menu, "Close")
button:SetSize(55, 30)
button:SetPos(10, 190)
button:SetClickFunction(function()
        menu:Close()
end)

local checkbox = cheadle_api.ImGui.Checkbox(menu, "sample checkbox")
checkbox:SetPos(10, 35)
checkbox:SetClickFunction(function()
        cheadle_api.Log("Checkbox toggled: " .. (checkbox:GetChecked() and "true" or "false"))
end)

local dropdown = cheadle_api.ImGui.Dropdown(menu, "sample dropdown", {"option1", "option2"})
dropdown:SetPos(10, 70)
dropdown:OnChangeFunction(function()
        cheadle_api.Log("Dropdown option selected: " .. dropdown:GetSelected())
end)

local slider = cheadle_api.ImGui.Slider(menu, "sample slider", 0, 10)
slider:SetPos(10, 110)
slider:OnChangeFunction(function()
        cheadle_api.Log("Slider changed: " .. slider:GetValue())
end)

local textbox = cheadle_api.ImGui.Textbox(menu, "sample textbox")
textbox:SetPos(10, 150)
textbox:OnChangeFunction(function()
        cheadle_api.Log("Textbox changed: " .. textbox:GetText())
end)
